'use client';
import { useState } from 'react';
import { ArrowUpRight, ArrowDown, Camera as Instagram, BookOpen, GraduationCap, BriefcaseBusiness, ArrowRight, Settings2 } from 'lucide-react';
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs';
import type { Content } from '@/lib/content';
export default function Profile({content}:{content:Content}) {
 const [category,setCategory]=useState('Semua');
 const items=content.items.filter(i=>i.published&&(category==='Semua'||i.kind===category));
 return <><div className="rainbow-line"/><a className="skip" href="#profil">Langsung ke profil</a><header className="site-header shell"><a className="personal-brand" href="/"><span className="brand-initial">RS<span>.</span></span><span>Risal Syahrir<small>PROFIL & KARYA</small></span></a><nav aria-label="Navigasi utama"><a href="#tentang">Tentang saya</a><a href="#karya">Karya & produk</a><a className="nav-contact" href={content.instagram || '#tentang'}>Mari terhubung <ArrowUpRight size={16}/></a></nav></header>
 <main><section className="profile-hero shell" id="profil"><div className="hero-text"><p className="kicker"><span/> ASN · WIDYAISWARA · ENTREPRENEUR</p><h1>{content.name}</h1><p className="job-title">{content.role}<span>pada {content.organization}</span></p><p className="intro">{content.intro}</p><div className="hero-actions"><a className="solid-button" href="#karya">Jelajahi karya saya <ArrowDown size={17}/></a>{content.instagram&&<a className="quiet-button" href={content.instagram} target="_blank" rel="noopener noreferrer"><Instagram size={18}/> Instagram <ArrowUpRight size={16}/></a>}</div></div>
 <aside className="identity-poster" aria-label="Identitas profesional"><div className="poster-top"><span>KENAL LEBIH DEKAT</span><span className="poster-dot"/></div><div className="poster-initial" aria-hidden="true">RS<span>.</span></div><div className="poster-title"><span>Belajar.</span><span>Bertumbuh.</span><span>Berbagi.</span></div><div className="poster-bottom"><span>IPDN XVIII</span><ArrowUpRight size={25}/></div><div className="brand-card"><span>USAHA SAYA</span><a href="https://lulusujian.com/" target="_blank" rel="noopener noreferrer"><img src="/assets/lulusujian-logo.png" alt="LulusUjian — Smart. Easy. Online." width="813" height="339"/></a></div></aside></section>
 <div className="role-band"><div className="shell"><span><GraduationCap/> Widyaiswara</span><span><BookOpen/> IPDN XVIII</span><span><BriefcaseBusiness/> LulusUjian.com</span></div></div>
 <section className="about-section shell" id="tentang"><div><p className="kicker">01 / TENTANG SAYA</p><h2>Mengenal saya<br/><span>lebih dekat.</span></h2></div><div className="about-copy">{content.bio.split('\n').filter(Boolean).map((p,i)=><p key={i}>{p}</p>)}<div className="role-note"><span className="note-line"/><p><strong>{content.role}</strong><br/>{content.organization}</p></div></div></section>
 <section className="work-section" id="karya"><div className="shell"><div className="section-top"><div><p className="kicker">02 / KARYA & PRODUK</p><h2>Ruang untuk<br/><span>karya saya.</span></h2></div><p>Jelajahi karya dan produk saya.<br/>Setiap tautan membawa Anda langsung<br className="desktop-break"/> ke informasi selengkapnya.</p></div><Tabs value={category} onValueChange={v=>setCategory(String(v))}><TabsList className="category-tabs" aria-label="Kategori karya">{['Semua','Karya','Produk'].map(c=><TabsTrigger value={c} key={c}>{c}</TabsTrigger>)}</TabsList></Tabs><div className="work-grid">{items.map(item=><article className="work-card" key={item.id}><a className={'work-image '+(item.image.includes('lulusujian-logo')?'logo-image':'')} href={item.url} target="_blank" rel="noopener noreferrer">{item.image?<img src={item.image} alt={item.title} loading="lazy" onError={e=>{e.currentTarget.style.display='none';}}/>:<BookOpen size={54} strokeWidth={1}/>}<span className="image-arrow"><ArrowUpRight/></span></a><div className="work-body"><span className="item-kind">{item.kind}</span><h3>{item.title}</h3><p>{item.description}</p><div className="work-bottom">{item.price&&<strong>{item.price}</strong>}<a href={item.url} target="_blank" rel="noopener noreferrer">{item.button}<ArrowUpRight size={18}/></a></div></div></article>)}</div>{!items.length&&<div className="empty-works"><BookOpen size={30}/><h3>Belum ada {category==='Semua'?'karya atau produk':category.toLowerCase()} yang ditampilkan.</h3><p>Silakan kembali untuk melihat pembaruan berikutnya.</p></div>}</div></section>
 {content.instagram&&<section className="connect-section shell"><div><p className="kicker">MARI TERHUBUNG</p><h2>Lanjutkan percakapan.</h2></div><a className="solid-button" href={content.instagram} target="_blank" rel="noopener noreferrer"><Instagram size={19}/> Temui saya di Instagram <ArrowRight size={18}/></a></section>}</main><footer className="site-footer shell"><p>{content.name}<span>Profil pribadi</span></p><a href="/kelola"><Settings2 size={15}/> Kelola profil</a></footer></>;
}
